# Generated by Django 3.1.3 on 2021-03-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurGallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('img', models.ImageField(upload_to='static/media')),
                ('jobrole', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.IntegerField(blank=True)),
                ('fb_url', models.CharField(blank=True, default='#', max_length=100)),
                ('insta_url', models.CharField(blank=True, default='#', max_length=100)),
                ('github_url', models.CharField(blank=True, default='#', max_length=100)),
                ('linkedn_url', models.CharField(blank=True, default='#', max_length=100)),
            ],
        ),
    ]
