# Generated by Django 3.1.3 on 2021-03-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourteams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourgallery',
            name='img',
            field=models.ImageField(upload_to='static/ourteams/media'),
        ),
    ]
